### PR TITLE
Some tweaks to the auth functionality

### PR DESCRIPTION
**Pull request by Bosphoramus**
Hi!

I made some changes so when an unauthenticated user tries to enter a protected route, he will be redirected to the login page.

Also, when a user is authenticated, he will see a link to the Dashboard instead of Login/Register on the index page.

Added a parameter to the useAuth hook to force a redirection to the dashboard only for authenticated users, this is useful for example on the Register/Login page where i implemented it.

Should have probably made the changes in separated commits, will try to improve that.

### CODE REVIEW

**Comment by Bosphoramus** [comment]
Will answer any questions in case there are any 👀

**Review by fzn0x — COMMENTED** [review]
can you replace `redirectToDashboardIfAuthenticated` with `redirectIfAuthenticated` ? because not all if authenticated will redirect to dashboard , we change the name to have a dynamic meaning.

**Comment by Bosphoramus** [comment]
@fncolon Yeah! nice idea.
Already changed it, made it so you can specify what route to redirect if the user is authenticated directly on the hook parameter.
Also renamed the parameter, sounds much better and concise that way ;)

**Comment by taylorotwell** [comment]
Thanks for contributing to Laravel! ❤️

**Pull request merged**
